### ISSUE TITLE
getting find_all error while trying to use

### ISSUE THREAD

**Issue by swolfand** [anthonywu/clippercard#7]
markup_type=markup_type))
Traceback (most recent call last):
  File "/usr/local/bin/clippercard", line 9, in <module>
    load_entry_point('clippercard==0.3.2', 'console_scripts', 'clippercard')()
  File "/Library/Python/2.7/site-packages/clippercard/main.py", line 69, in main
    print(clippercard.porcelain.tabular_output(session.user_profile, session.cards))
  File "/Library/Python/2.7/site-packages/clippercard/client.py", line 115, in user_profile
    return parser.parse_profile_data(self._dashboard_content)
  File "/Library/Python/2.7/site-packages/clippercard/parser.py", line 111, in parse_profile_data
    fields = profile_data.find_all('div', attrs={'class': 'fieldData'})
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by Yahosh** [comment]
I'm running into the same issue using Python 2.7.10 on OSX. Any info around this?

**Comment by egorvinogradov** [comment]
+1

**Comment by sermittens** [comment]
I changed all instances of "j_idt14" to "j_idt13" in client.py, which seems to have fixed things.

I found that in parser.py I was getting the login page, instead of the user profile page.

in client.py it was trying to login via: `'javax.faces.source': 'j_idt14:submitLogin'`

but on clippercard.com/ClipperCard/loginFrame.jsf the id was `'j_idt13:submitLogin'`

**Comment by goldengate88** [comment]
the development of this project has migrated to https://github.com/clippercard/clippercard-python

[recent fixes in 0.3.3 and later](https://github.com/clippercard/clippercard-python/pulls?q=is%3Apr+is%3Aclosed) contains the bug fix for this

**Comment by blai30** [comment]
@goldengate88 how does one use this clippercard API in swift?

**Comment by goldengate88** [comment]
@blai30 - unfortunately this project itself is not the API service. This project is an **unofficial** API *client* written in Python and only supports usage within a Python application. The proper way to take advantage of the principle of the implementation is to use this project's code as a reference implementation for writing a similar http client in Swift.

(A hacky, inelegant way to get around this is to [call a python process from within Swift](https://duckduckgo.com/?q=swift+call+python+process&atb=v100-7&ia=qa) but I highly discourage it because you're not going to be able to take advantage of the majority of the features within the library)

**Comment by anthonywu** [comment]
project has been refactored, closing issue due to staleness
